Flask Web App/website/blueprints/WorkoutPage.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, session
from .. import db
from ..models import Exercises, UserWorkout
from flask_login import current_user
from ..access import DbAccessSingleton

dbInstance = DbAccessSingleton.get_instance()

# Create a Blueprint object --> meaning it has a bunch of routes/URLs
# The first argument is the name of the blueprint, and the second argument is the name of the module
#  or package where the blueprint is located
WorkoutPage = Blueprint('WorkoutPage', __name__) 
    
@WorkoutPage.route('/exercises')
def get_exercises():
    exercises = Exercises.query.all()
    exercisesList = [{'name': exercise.name, 'muscleGroup': exercise.muscleGroup, 'equipType': 
                       exercise.equipType} for exercise in exercises]
    return jsonify(exercisesList)

@WorkoutPage.route('/WorkoutPage', methods=['GET', 'POST'])
def workoutPage():
    if request.method == 'POST':
        name = request.form['name']
        muscleGroup = request.form['muscleGroup']
        equipType = request.form['equipType']

        exercises = Exercises(name=name, muscleGroup=muscleGroup, equipType=equipType)
        db.session.add(exercises)
        db.session.commit()

        return redirect(url_for('WorkoutPage.workoutPage'))

    result = dbInstance.custom_query("SELECT DISTINCT WorkoutName FROM SavedWorkouts WHERE UserID = " + f"'{current_user.email}'")
    result = list(result)
    workoutNames = [name[0] for name in result]
    # Render the template for GET requests
    return render_template('WorkoutPage.html', user=current_user, workoutNames=workoutNames)
    
@WorkoutPage.route('/save_workout', methods=['POST'])
def save_workout():
    # Get the workout data from the request
    workoutData = request.json.get('workoutData')
    workoutObj = UserWorkout(workoutData)
    # Print the workout to the console
    # workoutObj.printWorkout()    
    # Save the workout to the database
    workoutObj.save_workout_db()
    return render_template('home.html', user=current_user)


@WorkoutPage.route('/save_workout_data', methods=['POST'])
def save_workout_data():
    if request.method == 'POST':
        # Extract recommendation data from the request
        workoutName = request.json.get('workoutName')
        workoutData = request.json.get('workoutData')
        recommendation = [exercise['exerciseName'] for exercise in workoutData['exercises']]
        
        preselectedInfo = {}

        for exercise in workoutData['exercises']:
            preselectedInfo[exercise['exerciseName']] = {'sets': exercise['sets'], 'reps': exercise['reps'], 'weights': exercise['weight'], 'loaded': False}
        # Save the recommendation data in the session
        session['recommendation'] = recommendation
        #Save the preselected info in the session
        session['preselectedInfo'] = preselectedInfo
        
        # Redirect to the same route with a GET request
        return redirect(url_for('WorkoutPage.save_workout_data'))

@WorkoutPage.route('/save_workout_data', methods=['GET'])
def get_recommendation():
    # Retrieve recommendation data from the session
    recommendation = session.get('recommendation', [])
    preselectedInfo = session.get('preselectedInfo', {})

    result = dbInstance.custom_query("SELECT DISTINCT WorkoutName FROM SavedWorkouts WHERE UserID = " + f"'{current_user.email}'")
    result = list(result)
    workoutNames = [name[0] for name in result]
    # Figure out the best place to clear session data
    return render_template('ModifiedWorkoutPage.html', recommendation=recommendation, preselectedInfo=preselectedInfo, workoutNames=workoutNames, user=current_user)

# Displays recommended workout based on user input
@WorkoutPage.route('/Result', methods=['GET', 'POST'])
def result():
    muscleGroup = request.args.get('muscle_group')
    equipment = request.args.get('equipment')
    recommendation = fetch_recommendation(muscleGroup, equipment)
    recommendation = [sublist[0] for sublist in recommendation]
    user = current_user if current_user.is_authenticated else None

    result = dbInstance.custom_query("SELECT DISTINCT WorkoutName FROM SavedWorkouts WHERE UserID = " + f"'{current_user.email}'")
    result = list(result)
    workoutNames = [name[0] for name in result]
    return render_template('Result.html', recommendation=recommendation, workoutNames=workoutNames, user=user)

def fetch_recommendation(muscleGroup, equipment):
    # Use the search method from DbAccessSingleton to fetch data from the database
    result = dbInstance.custom_query(f'SELECT Name FROM Exercises WHERE EquipType = "{equipment}" AND MuscleGroup = "{muscleGroup}"')

    # Return the recommendation if found, otherwise return a default message
    return result if result else "No workout recommendation found for the selected Muscle Group and Equipment."

Flask Web App/website/blueprints/calender.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, session
from .. import db
from ..models import Exercises, ScheduledWorkouts, UserWorkout
from flask_login import current_user
from ..access import DbAccessSingleton
from sqlalchemy.exc import IntegrityError

DATABASE = 'Flask Web App\instance\database.db'

# Create a Blueprint object
calender = Blueprint('calender', __name__)

@calender.route('/Calender')
def calendar():
    return render_template('Calender.html', user=current_user)

@calender.route('/exercises', methods=['GET'])
def get_exercises():
    exercises = Exercises.query.all()
    exercisesList = [{'name': exercise.name, 'muscleGroup': exercise.muscleGroup, 'equipType': 
                       exercise.equipType} for exercise in exercises]
    return jsonify(exercisesList)

@calender.route('/workout_names', methods=['GET'])
def get_workout_names():
    dbInstance = DbAccessSingleton.get_instance()
    result = dbInstance.custom_query("SELECT DISTINCT workoutName FROM SavedWorkouts WHERE UserID = " + f"'{current_user.email}'")
    workoutNames = [row[0] for row in result]
    return jsonify(workoutNames)

@calender.route('/save_scheduled_workout', methods=['POST'])
def save_scheduled_workout():
    try:
        workoutData = request.get_json()['workoutData']
        scheduledWorkout = ScheduledWorkouts(date=workoutData['date'], workoutName=workoutData['workoutName'], userID=current_user.email)
        db.session.add(scheduledWorkout)
        db.session.commit()
        return 'Scheduled workout data saved successfully.', 200
    except IntegrityError:
        db.session.rollback()
        return 'ERROR:  You already have a workout scheduled for that day.', 400
    except Exception as e:
        db.session.rollback()
        return f'Error: {str(e)}', 500

@calender.route('/get_scheduled_workouts', methods=['GET'])
def get_scheduled_workouts():
    try:
        date = request.args.get('date')
        user_id = current_user.email
        scheduled_workouts = ScheduledWorkouts.query.filter_by(date=date, userID=user_id).all()
        workout_names = [workout.workoutName for workout in scheduled_workouts]
        return jsonify(workout_names), 200
    except Exception as e:
        return f'Error: {str(e)}', 500

Flask Web App/website/blueprints/recommender.py
# recommender.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for
from .. import db
from ..models import Exercises
from flask_login import current_user

DATABASE = 'Flask Web App\instance\database.db'

# Create a Blueprint object
RecommenderBP = Blueprint('recommender', __name__)

@RecommenderBP.route('/Recommender')
def recommender():
    return render_template('Home.html', user=current_user)

@RecommenderBP.route('/exercises', methods=['GET'])
def get_exercises():
    exercises = Exercises.query.all()
    exercisesList = [{'name': exercise.name, 'muscleGroup': exercise.muscleGroup, 'equipType': 
                       exercise.equipType} for exercise in exercises]
    return jsonify(exercisesList)

Flask Web App/website/blueprints/views.py
from flask import Blueprint, render_template, request, redirect, url_for # Import the Blueprint class from the flask package
from flask_login import login_required, current_user
from ..models import Note, UserWorkout
from .. import db
import json
from ..access import DbAccessSingleton

dbInstance = DbAccessSingleton.get_instance()

# Create a Blueprint object --> meaning it has a bunch of routes/URLs
views = Blueprint('views', __name__) # The first argument is the name of the blueprint, and the second argument is the name of the module or package

@views.route('/', methods=['GET', 'POST']) # This is a decorator that tells Flask what URL to trigger the function
@login_required # This is a decorator that tells Flask we need to login before accessing the home page
def home():
    if request.method == 'POST':
        muscle_group = request.form.get('MuscleGroup') #get to getlist and muscle_group to muscle_groups for multi selec
        equipment = request.form.get('Equipment')

        return redirect(url_for('WorkoutPage.result', muscle_group=muscle_group, equipment=equipment)) #return redirect(url_for('WorkoutPage.result', muscle_groups=','.join(muscle_groups), equipment=equipment))#for multi musc selec

    else:
        workoutNames = []
        workoutList = []
        dbInstance = DbAccessSingleton.get_instance()
        result = dbInstance.custom_query("SELECT DISTINCT WorkoutName FROM SavedWorkouts WHERE UserID = " + f"'{current_user.email}'")
        result = list(result)
        for name in result:
            tempName = name[0]
            workoutNames.append(tempName)
        for name in workoutNames:
            workoutObj = UserWorkout({'name': name, 'exercises': []})
            workoutObj.get_workout_db()
            workoutList.append(workoutObj)
        # print(workoutList)
        # workoutObj = UserWorkout({'name': workoutName, 'exercises': []})
        # workoutObj.getWorkoutDB(workoutName)
        # workoutObj.printWorkout()#Below was WorkoutViewer
        return render_template("WorkoutViewer.html", user=current_user, workoutList=workoutList)

Flask Web App/website/templates/ModifiedWorkoutPage.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1 class="app-title">Create Workout</h1>
        <!-- Text field for workout name -->
        <div class="form-group">
            <label for="workoutName">Workout Name:</label>
            <!-- Limiting the width of the text field -->
            <input type="text" id="workoutName" name="workoutName" placeholder="Enter Workout Name">
            <p id="workoutNameError" style="color: red; display: none;">Please enter a workout name</p>
            <p id="workoutNameExistsError" style="color: red; display: none;">Workout name already exists</p>
        </div>
        <button id="addExerciseButton" class="btn btn-primary">Add Exercise</button>
        <p class="app-title">Current Exercises</p>
        <div id="workoutPage">
            <!-- Workouts will be dynamically added here -->
        </div>
        <button id="submitWorkoutButton" class="btn btn-success float-right">Submit Workout</button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="addExerciseModal" tabindex="-1" role="dialog" 
        aria-labelledby="addExerciseModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addExerciseModalLabel">Add Exercise</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <ul id="exerciseList" class="list-group">
                        <!-- Workouts will be dynamically added here -->
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block additional_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='WorkoutPage.css') }}"> 
    <link rel="stylesheet" href="{{ url_for('static', filename='DarkTheme.css') }}"> 
{% endblock %}
{% block javascript %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- Pre-select exercises based on the recommendation array -->
    <script>
        var preSelectedExercises = "{{ recommendation | safe }}";
        var preselectedInfo = {{ preselectedInfo | tojson | safe}};
        var workoutNames = "{{ workoutNames | safe }}";
    </script>
    <script src="{{ url_for('static', filename='WorkoutPage.js') }}"></script>
{% endblock %}

Flask Web App/website/templates/Recommender.html
{% extends "Base.html" %}
{% block title %}Recommender{% endblock %}

{% block additional_css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='Recommender.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='DarkTheme.css') }}">
{% endblock %}

{% block content %}
<div>
    <div>
        <form method="post" action="{{ url_for('recommender') }}" style="text-align: center;">
            <h3>Recommender</h3>
            <div class="form-group">
                <label for="MuscleGroup">Muscle Group</label>
                <select class="form-control" id="MuscleGroup" name="MuscleGroup">
                    <option value="Chest">Chest</option>
                    <option value="Back">Back</option>
                    <option value="Legs">Legs</option>
                    <option value="Arms">Arms</option>
                    <option value="Abs">Abs</option>
                </select>
            </div>
            <div class="form-group">
                <label for="Equipment">Available Equipment</label>
                <select class="form-control" id="Equipment" name="Equipment">
                    <option value="Body Weight">BodyWeight</option>
                    <option value="Dumbbell">Dumbbell</option>
                    <option value="Full Gym">FullGym</option>
                </select>
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

Flask Web App/website/templates/Result.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1 class="app-title">Recommended Workout</h1>
        <div class="form-group">
            <label for="workoutName">Workout Name:</label>
            <!-- Limiting the width of the text field -->
            <input type="text" id="workoutName" name="workoutName" placeholder="Enter Workout Name">
            <p id="workoutNameError" style="color: red; display: none;">Please enter a workout name</p>
            <p id="workoutNameExistsError" style="color: red; display: none;">Workout name already exists</p>
        </div>
        <button id="addExerciseButton" class="btn btn-primary">Add Exercise</button>
        <p class="app-title">Current Exercises</p>
        <div id="workoutPage">
            <!-- Workouts will be dynamically added here -->
        </div>
        <button id="submitWorkoutButton" class="btn btn-success float-right">Submit Workout</button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="addExerciseModal" tabindex="-1" role="dialog" 
        aria-labelledby="addExerciseModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addExerciseModalLabel">Add Exercise</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <ul id="exerciseList" class="list-group">
                        <!-- Workouts will be dynamically added here -->
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block additional_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='WorkoutPage.css') }}"> 
    <link rel="stylesheet" href="{{ url_for('static', filename='DarkTheme.css') }}"> 
{% endblock %}
{% block javascript %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- Pre-select exercises based on the recommendation array -->
    <script>
        var preSelectedExercises = "{{ recommendation | safe }}";
        var workoutNames = "{{ workoutNames | safe }}";
    </script>
    <script src="{{ url_for('static', filename='WorkoutPage.js') }}"></script>
{% endblock %}

Flask Web App/website/templates/SignUp.html
{% extends "Base.html" %} 
{% block title %}Sign Up{% endblock %}

{% block additional_css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='DarkTheme.css') }}">

{% endblock %}
{% block content %}
    <form method="post">
        <h3 align="center">Sign Up</h3>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input 
                type="email" 
                class="form-control" 
                id="email" 
                name="email" 
                placeholder="Enter email"
            />
        </div>
        <div class="form-group">
            <label for="firstName">First Name</label>
            <input 
                type="text" 
                class="form-control" 
                id="firstName" 
                name="firstName" 
                placeholder="Enter first name"
            />
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input 
                type="password" 
                class="form-control" 
                id="password1" 
                name="password1" 
                placeholder="Enter password"
            />
        </div>
        <div class="form-group">
            <label for="password2">Confirm Password</label>
            <input 
                type="password" 
                class="form-control" 
                id="password2" 
                name="password2" 
                placeholder="Confirm password"
            />
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

Flask Web App/website/templates/WorkoutPage.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1 class="app-title">Create Workout</h1>
        <!-- Text field for workout name -->
        <div class="form-group">
            <label for="workoutName">Workout Name:</label>
            <!-- Limiting the width of the text field -->
            <input type="text" id="workoutName" name="workoutName" placeholder="Enter Workout Name">
            <p id="workoutNameError" style="color: red; display: none;">Please enter a workout name</p>
            <p id="workoutNameExistsError" style="color: red; display: none;">Workout name already exists</p>
        </div>
        <button id="addExerciseButton" class="btn btn-primary">Add Exercise</button>
        <p class="app-title">Current Exercises</p>
        <div id="workoutPage">
            <!-- Workouts will be dynamically added here -->
        </div>
        <button id="submitWorkoutButton" class="btn btn-success float-right">Submit Workout</button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="addExerciseModal" tabindex="-1" role="dialog" 
        aria-labelledby="addExerciseModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addExerciseModalLabel">Add Exercise</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <ul id="exerciseList" class="list-group">
                        <!-- Workouts will be dynamically added here -->
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block additional_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='WorkoutPage.css') }}"> 
    <link rel="stylesheet" href="{{ url_for('static', filename='DarkTheme.css') }}"> 
{% endblock %}
{% block javascript %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        var preSelectedExercises = null;
        var workoutNames = "{{ workoutNames | safe }}";
    </script>
    <script src="{{ url_for('static', filename='WorkoutPage.js') }}"></script>
{% endblock %}

Flask Web App/website/templates/WorkoutViewer.html
{% extends "base.html" %}
{% block content %}
    <h1>Welcome, {{ user.username }}!</h1>
    <h2>Choose a Workout:</h2>
    <div id="workout-container">
        {% for workout in workoutList %}
        <div class="workout-block">
            <h3>{{ workout.workoutName }}</h3>
            <ul>
                {% for exercise in workout.exerciseList %}
                <li>{{ exercise.exerciseName }}</li>
                <ul>
                    <li>&emsp;Sets: 
                        {{ exercise.sets }}
                    </li>
                    <li>&emsp;Reps:
                        {% for rep in exercise.reps %}
                            {{ rep }}{% if not loop.last %}, {% endif %}
                        {% endfor %}
                    </li>
                </ul>
                {% if not loop.last %}
                <hr> <!-- Add a horizontal line between exercises -->
                {% endif %}
                {% endfor %}
            </ul>
            <button class="start-workout-btn" data-workout="{{ workout.workoutName }}" data-workout-data='{{ workout.to_dict()|tojson }}'>Start Workout</button>
        </div>
        {% endfor %}
    </div>

{% endblock %}
{% block additional_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='WorkoutViewer.css') }}">
{% endblock %}
{% block javascript %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="{{ url_for('static', filename='WorkoutViewer.js') }}"></script>
{% endblock %}

Flask Web App/website/templates/base.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link 
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
    />
    <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='Base.css') }}">
    {% block additional_css %}{% endblock %}
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>  
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbar"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class = "collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" id="home" href="/">Home</a>
                    <a class="nav-item nav-link" id="recommender" href="/Recommender">Recommender</a>
                    <a class="nav-item nav-link" id="calendar" href="/Calender">Calender</a>
                    <a class="nav-item nav-link" id="workout" href="/WorkoutPage">Workout Page</a>
                    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" id="login" href="/Login">Login</a>
                    <a class="nav-item nav-link" id="signUP" href="/Sign-up">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category,message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}

        <div class = "container">
            {% block content %}
            {% endblock %}
        </div>
        <!-- The links below are loading javascript bootstraps -->
        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"
        ></script>
        {% block javascript %}
            <script type="text/javascript">
                function deleteNote(noteId) {
            fetch("/delete-note", {
                method: "POST",
                body: JSON.stringify({ noteId: noteId }),
            }).then((_res) => {
                window.location.href = "/";
            });
            }
        </script>
        {% endblock %}

    </body>
</html>

Flask Web App/website/templates/calender.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <div style="text-align: center;">
    <h2>Schedule Workout</h2>
    <div id="calendarContainer">
        <p id="selectedDate"></p>
        <p id="demo"></p>
        <div style="display: flex; justify-content: space-between; width: 200px;">
            <select id="monthElement" onchange="load_calendar()"></select>
            <select id="yearElement" onchange="load_calendar()"></select>
        </div>
        <table id="calendarElement">
            <tr>
                <th>Sun</th>
                <th>Mon</th>
                <th>Tue</th>
                <th>Wed</th>
                <th>Thu</th>
                <th>Fri</th>
                <th>Sat</th>
            </tr>
        </table>
        <button id="scheduleWorkoutButton">Schedule Workout</button>
    </div>
    <select id="workoutDropdown"></select>
    <div id="workoutsContainer"></div>
</body>
</html>
{% endblock %}
{% block additional_css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='Calender.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='DarkTheme.css') }}">
{% endblock %}
{% block javascript %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="{{ url_for('static', filename='Calender.js') }}"></script>
{% endblock %}

Flask Web App/website/templates/home.html
{% extends "Base.html" %} 
{% block title %}Home{% endblock %}

{% block content %}
        <form method="post" action="{{ url_for('views.home') }}" style="text-align: center;">
            <h3>Recommender</h3>
            <div class="form-group">
                <!--
                <label for="MuscleGroup">Muscle Group</label>
                <br>
                <input type="checkbox" id="Chests" name="MuscleGroup" value="Chest">
                <label for="Chest">Chest</label>
                <input type="checkbox" id="Back" name="MuscleGroup" value="Back">
                <label for="Back">Back</label>
                <input type="checkbox" id="Legs" name="MuscleGroup" value="Legs">
                <label for="Legs">Legs</label>
                <input type="checkbox" id="Arms" name="MuscleGroup" value="Arms">
                <label for="Arms">Arms</label>
                <input type="checkbox" id="Abs" name="MuscleGroup" value="Abs">
                <label for="Abs">Abs</label> 
                -->
                <select class="form-control" id="MuscleGroup" name="MuscleGroup">
                    <option value="Chest">Chest</option>
                    <option value="Back">Back</option>
                    <option value="Legs">Legs</option>
                    <option value="Arms">Arms</option>
                    <option value="Abs">Abs</option>
                    <!--
                    {% for group in muscle_groups %}
                    <div class="form-check">
                        <input type='checkbox' id="{{ group }}" name="MuscleGroup" value="{{ group }}">
                        <label for="{{ group }}">{{ group }}</label>
                    </div>
                    {% endfor %}
                    -->
               </select>
            </div>
            <div class="form-group">
                <label for="Equipment">Available Equipment</label>
                <select class="form-control" id="Equipment" name="Equipment">
                    <option value="Body Weight">BodyWeight</option>
                    <option value="Dumbbell">Dumbbell</option>
                    <option value="Full Gym">FullGym</option>
                </select>
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}
{% block additional_css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='DarkTheme.css') }}">
{% endblock %}